# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.5/c2cciutils/schema.json

checks:
  codespell: false
  black: false
  isort: false

audit:
  snyk:
    pip_install_arguments:
      - --user
      - --ignore-installed
