# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.4/c2cciutils/schema.json

checks:
  codespell:
    arguments:
      - --quiet-level=2
      - --check-filenames
      - --ignore-words-list=nd

publish:
  docker: false

audit:
  snyk:
    pip_install_arguments:
      - --user
      - --ignore-installed
