# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.2.14/c2cciutils/schema.json

checks:
  versions:
    rebuild: False
  codespell: False
  required_workflows: False

publish:
  docker:
    images:
      - name: camptocamp/jsonschema-gentypes
